spring:
  application:
    name: qingsong-gateway
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://qingsong-mysql:3306/db_qingsong?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf
    username: root
    password: 123456
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
#      config:
#        file-extension: yaml
#        shared-configs:
#          - data-id: default-springmvc.yaml
#            refresh: true
#          - data-id: default-redis.yaml
#            refresh: true
#          - data-id: default-rabbitmq.yaml
#            refresh: true

server:
  port:
    7960
